%==========================================================================
%                       Travis Moleski/Rhett Huston
%
%                     FILE CREATION DATE: 10/19/2022
%
%                      Bulk_Training_Data_Extract.m
%
% This program looks at a ROSBAG generated by the Ohio University van and
% sequentially grabs training data based on which rings fall inside a roi
%
%==========================================================================

%% Clear & Setup Workspace
clc; clear; close all
format compact

% warning('CHECK THESE VARS: xy_roi Filename xyzir_front xyzir_REAR!!!!!!!')
% disp('Pausing until ready...')
% pause

%% Options

roi_select = 1;

%% Variable Initiation
LiDAR_Ref_Frame             = [0; 1.584; 1.444];
IMU_Ref_Frame               = [0; 0.336; -0.046];

% Correction frame:         LiDAR_Ref_Frame - IMU_Ref_Frame [Y X Z]
gps_to_lidar_diff           = [(LiDAR_Ref_Frame(1) - IMU_Ref_Frame(1)), (LiDAR_Ref_Frame(2) - IMU_Ref_Frame(2)), (LiDAR_Ref_Frame(3) - IMU_Ref_Frame(3))]; 

raw_data_export = {};

%% Loading the ROSBAG

% Location of rosbag
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/shortened_Simms/2022-10-11-09-24-00.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/shortened_Simms/2022-10-11-09-28-18.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/shortened_Simms/2022-10-11-09-29-34.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/shortened_Simms/2022-10-11-09-31-55.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/shortened_Simms/2022-10-11-09-33-39.bag';

% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Coach_Sturbois_Shortened/sturbois_curve_1.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Coach_Sturbois_Shortened/sturbois_straight_1.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Coach_Sturbois_Shortened/sturbois_woods_2.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Coach_Sturbois_Shortened/sturbois_woods_3.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Coach_Sturbois_Shortened/sturbois_woods_4.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Coach_Sturbois_Shortened/sturbois_woods_5.bag';

% chipseal (_1 - _5)
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Coach_Sturbois_Shortened/sturbois_chipseal_woods_1.bag';


% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-13-35_GRAV.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-14-05_GRAV.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-14-36_GRAV.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-11-15-07_GRAV.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-11-16-01_GRAV.bag';

% grass - use different channels
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-21-54_CHIP.bag';

% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-16-43_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-17-06_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-17-31_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-17-56_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-20-40_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-21-54_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-22-55_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-23-34_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-24-24_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-25-18_CHIP.bag';
% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-26-11_CHIP.bag';

% file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/shortened_gravel_lot/2022-10-20-16-56-40_GRAV.bag';

% % Load the rosbag into the workspace
% disp('Loading ROSBAG')
% bag = rosbag(file);
% disp('ROSBAG Loaded')
% 
% % Topics
% disp('Loading Messages...')
% topics = bag.AvailableTopics;
%           
% disp('Loading LIDAR Messages...')
% lidar_topic = select(bag,'Topic','velodyne_points');
% lidar_msgs = readMessages(lidar_topic, 'DataFormat', 'struct');
% 
% disp('Loading GPS Messages... ')
% gps_topic = select(bag,'Topic','/gps/gps');
% gps_msgs = readMessages(gps_topic, 'DataFormat', 'struct');
% 
% disp('Messages Loaded')

%% Loading the ROIs

% These are gravel files
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_curve.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_straight.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_woods_2.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_woods_3.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_woods_4.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_woods_5.mat');

% These are gravel files
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_chipseal_woods_5.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_chipseal_woods_2.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_chipseal_woods_4.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_chipseal_woods_1.mat');

% These are foliage/grass files
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_gras_foli_sturbois_curve_1_all.mat');

% These are grass files
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-17-31_CHIP_ALL_for_grass.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_sturbois_straight_1_all_grass');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-21-54_CHIP_ALL_for_grass.mat');

% These are foliage files
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-13-35_GRAV_ALL_foliage.mat');

% These are gravel files
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-13-35_GRAV.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-14-05_GRAV.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-14-36_GRAV.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-11-15-07_GRAV.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-11-16-01_GRAV.mat');

% These are chip files
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-16-43_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-17-06_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-17-31_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-17-56_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-20-40_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-21-54_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-22-55_CHIP.mat');

% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-23-34_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-24-24_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-25-18_CHIP.mat');
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-26-11_CHIP.mat');

% These are gravel files
% roi_file = ('/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-16-56-40_GRAV.mat');

%% roi/rosbag PAIRS - 1 ROI per file

% Gravel Lot 1
% roi_file = '/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/man_roi/Manual_Classified_PCD_arc_width_controlol.mat.mat';
% bag_file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/gravel_lot/2023-03-09-14-46-23.bag';
% terrain_opt = 1;

% Gravel Lot 2, 3
% roi_file = '/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/man_roi/Manual_Classified_PCD_gravel_lot_2_2rois.mat';
% bag_file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/gravel_lot/2023-03-14-13-12-31.bag';
% terrain_opt = 1;
% roi_select = 2;

% Lawn Grass 1
% roi_file = '/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-17-31_CHIP_ALL_for_grass.mat';
% bag_file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-17-31_CHIP.bag';
% terrain_opt = 4;

% Lawn Grass 2
% roi_file = '/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/TRAINING_PCD_EXPORT/Manual_Classified_PCD_2022-10-20-10-21-54_CHIP_ALL_for_grass.mat';
% bag_file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/Armitage_Shortened_Bags/2022-10-20-10-21-54_CHIP.bag';
% terrain_opt = 4;

% Pavement 1, 2
% roi_file = '/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/man_roi/Manual_Classified_PCD_pavement_1_roi.mat.mat';
% bag_file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/03_13_2023_shortened_coach_sturbois/2023-03-13-10-56-38.bag';
% terrain_opt = 5;
% roi_select = 2; %1,2

% Lawn Grass 3
% roi_file = '/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/man_roi/Manual_Classified_PCD_blue_route_grass_roi.mat';
% bag_file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/blue_short/2023-03-15-14-09-13.bag';
% terrain_opt = 4;
% roi_select = 1;

% Pavement 3, 4 - blue_route
roi_file = '/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/man_roi/Manual_Classified_PCD_blue_route_asphalt_roiz.mat';
bag_file = '/media/autobuntu/chonk/chonk/DATA/chonk_ROSBAG/blue_short/2023-03-15-14-09-13.bag';
terrain_opt = 5;
roi_select = 1; %1,2,3


%% Load Stuff

% Load the rosbag into the workspace
disp('Loading ROSBAG')
bag = rosbag(bag_file);
disp('ROSBAG Loaded')

% Topics
disp('Loading Messages...')
topics = bag.AvailableTopics;
          
disp('Loading LIDAR Messages...')
lidar_topic = select(bag,'Topic','velodyne_points');
lidar_msgs = readMessages(lidar_topic, 'DataFormat', 'struct');

disp('Loading GPS Messages... ')
gps_topic = select(bag,'Topic','/gps/gps');
gps_msgs = readMessages(gps_topic, 'DataFormat', 'struct');

disp('Messages Loaded')

% Load the ROI file
load(roi_file);

%% MCA Terrain Select

% disp('Select terrain type')
% dlg_list                    = {'Gravel', 'Chipseal', 'Foliage', 'Grass', 'Asphalt'};
% [terrain_opt,~]           = listdlg('ListString', dlg_list,'SelectionMode','single');

%% Save Location

time_now        = datetime("now","Format","uuuuMMddhhmmss");
time_now        = datestr(time_now,'yyyyMMddhhmmss');

[~, bag_name] = fileparts(bag_file);

if terrain_opt == 1
    save_folder = "/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/Save_Bulk_All_4/Grav/" + string(bag_name)
    terrain_type = 'gravel';
elseif terrain_opt == 2
    save_folder = "/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/Save_Bulk_All_4/Chip/" + string(bag_name)
    terrain_type = 'chipseal';
elseif terrain_opt == 3
    save_folder = "/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/Save_Bulk_All_4/Foli/" + string(bag_name)
    terrain_type = 'foliage';
elseif terrain_opt == 4
    save_folder = "/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/Save_Bulk_All_4/Gras/" + string(bag_name)
    terrain_type = 'grass';
elseif terrain_opt == 5
    save_folder = "/media/autobuntu/chonk/chonk/git_repos/Rural-Road-Lane-Creator/Random_Forest/Save_Bulk_All_4/Asph/" + string(bag_name)
    terrain_type = 'asphalt';
end

mkdir(save_folder)
addpath(save_folder)

%% More Var Init

% cloud_break                 = 150;
cloud_break                 = length(lidar_msgs);
gps_pos_store               = zeros(cloud_break,3);
lidar_pos_store             = gps_pos_store;

% minimum/maximum distance cut-off
min_dist                    = 2.25;
max_dist                    = 10;

% % Closest 2 rings
% ring_min                    = 10;
% ring_max                    = 1;
% 
% % Furthest 10 rings - foliage
% ring_min                    = 31;
% ring_max                    = 20;

% Closest 8 rings - grass
% ring_min = 7;
% ring_max = 1;

% Closest 3-8 rings - grass 2022-10-20-10-21-54
% ring_min = 7;
% ring_max = 3;

% All Rings
ring_min = 32;
ring_max = 1;

% RANSAC - MATLAB
maxDistance                 = 0.5;

%% Checkaronis

manual_classifier_pcd_display(roi_file, lidar_msgs, gps_msgs, ring_min, ring_max, min_dist, max_dist, terrain_opt, roi_select)

disp('Waiting until ready!')
pause

close all

%% Timestamps

% Matching timestamps
[indexes, fromTimes, toTimes, diffs] = matchTimestamps(lidar_msgs, gps_msgs);

%Find which GPS message matches the first scan
matchedLidar                = lidar_msgs{1};
matchedGps_init             = gps_msgs{indexes(1)};

%% Initilizing the starting point
% Select reference point as first GPS reading (local)
origin = [matchedGps_init.Latitude, matchedGps_init.Longitude, matchedGps_init.Altitude];

% Setting the offset from the gps orientation to the lidar
% takes gps emu to local frame of lidar
gps2lidar = [ cosd(90) sind(90) 0;
             -sind(90) cosd(90) 0;
             0       0          1]; 
         
% Setting the (gps_to_lidar_diff) offset from the lidar offset to the gps
LidarOffset2gps = [ cosd(90) -sind(90)  0;
                    sind(90)  cosd(90)   0;
                    0        0           1]; 

%% Doing the data
fprintf('Max time delta is %f sec \n',max(abs(diffs)));

h = waitbar(0, "Grabbing the dataz...");
for cloud = 1:length(lidar_msgs)
    
    %% Grabbing Data
    
    % Reading the current point cloud and matched gps coord
    current_cloud               = lidar_msgs{cloud};
    matched_stamp               = gps_msgs{indexes(cloud)};
    
    % Converting the gps coord to xyz (m)
    [xEast, yNorth, zUp]        = latlon2local(matched_stamp.Latitude, matched_stamp.Longitude, matched_stamp.Altitude, origin);
    
    % Grabbing the angles
    roll                        = matched_stamp.Roll;
    pitch                       = matched_stamp.Pitch;
    yaw                         = matched_stamp.Track+180;
    
    %% Rectifying Frames
     
    % Creating the rotation matrix
    rotate_update               = rotz(90-yaw)*roty(roll)*rotx(pitch);
     
    % Comment Here
    groundTruthTrajectory       = [xEast, yNorth, zUp] * gps2lidar ;
    
    % Comment Here
    gps_to_lidar_diff_update    = gps_to_lidar_diff * LidarOffset2gps * rotate_update;

    % Comment Here
    LidarxEast                  = groundTruthTrajectory(1)  + gps_to_lidar_diff_update(1);
    LidaryNorth                 = groundTruthTrajectory(2)  + gps_to_lidar_diff_update(2);
    LidarzUp                    = groundTruthTrajectory(3)  + gps_to_lidar_diff_update(3);

    % Comment here
    groundTruthTrajectory       = groundTruthTrajectory;
    lidarTrajectory             = [LidarxEast, LidaryNorth, LidarzUp];
    
    % Reading the current cloud for xyz, intensity, and ring (channel) values
    xyz_cloud                   = rosReadXYZ(current_cloud);
    intensities                 = rosReadField(current_cloud, 'intensity');
    ring                        = rosReadField(current_cloud, 'ring');
    xyz_cloud(:,4)              = intensities;
    xyz_cloud(:,5)              = ring;
    
    %% RANSAC and MLS
    
    ptCloudSource = pointCloud([xyz_cloud(:,1), xyz_cloud(:,2), xyz_cloud(:,3)], 'Intensity',  xyz_cloud(:,4));
    x_ptA                       = ptCloudSource.Location(:,1);
    y_ptA                       = ptCloudSource.Location(:,2);
    z_ptA                       = ptCloudSource.Location(:,3);
    xyz_mll                     = [x_ptA y_ptA z_ptA];
    model_MLS                   = MLL_plane_proj(xyz_mll(isfinite(xyz_mll(:,1)), :));
    % RANSAC - MATLAB
%     maxDistance                 = 0.5;
    model_RANSAC                = pcfitplane(ptCloudSource, maxDistance);

    %% Doing Other Stuff
    
    % Eliminate points
%     xyz_cloud(xyz_cloud(:,5) < ring_max, :) = [];
%     xyz_cloud(xyz_cloud(:,5) > ring_min, :) = [];

%     xyz_cloud(sqrt(xyz_cloud(:,1).^2 + xyz_cloud(:,2).^2 + xyz_cloud(:,3).^2) <= min_dist, :) = [];
%     xyz_cloud(sqrt(xyz_cloud(:,1).^2 + xyz_cloud(:,2).^2 + xyz_cloud(:,3).^2) >= max_dist, :) = [];
    
    
    % Eliminiating infs and nans from the xyz data - there may be a way to
    % use the 
    xyz_cloud                   = xyz_cloud( ~any( isnan(xyz_cloud) | isinf(xyz_cloud), 2),:);
    
    % Transforming the point cloud
    tform                       = rigid3d(rotate_update, [lidarTrajectory(1) lidarTrajectory(2) lidarTrajectory(3)]);
    
    % EXPERIMENT sort rows
    xyz_cloud = sortrows(xyz_cloud,5);
    
    % Creating the point cloud object
%     pointClouXYZI_curr          = pointCloud([xyz_cloud(:,1), xyz_cloud(:,2), xyz_cloud(:,3)], 'Intensity',  xyz_cloud(:,4));
%     pointClouXYZI_curr          = pctransform(pointClouXYZI_curr, tform);
    
    %% Grabbing the training data from the point cloud
    [data_a data_b] = grab_training_data(xyz_cloud, tform, Manual_Classfied_Areas, model_RANSAC, model_MLS, save_folder, terrain_opt, roi_select);
    
    raw_data_export = [raw_data_export; data_a; data_b];
    
    % Plotting gps/lidar frames
%     gps_pos_store(cloud,:)      = groundTruthTrajectory;
%     lidar_pos_store(cloud,:)    = lidarTrajectory;
    
    %% Save point cloud
%     pointCloudList{cloud}       = pointClouXYZI_curr;
    
    % alternate method - eliminates points though 
%     mergeGridStep = 0.1;
%     pointCloudList = pcmerge(pointCloudList, pointClouXYZI_curr, mergeGridStep);
    
    %% Break Condition
    
    if cloud > cloud_break
        break
    end
    

end

delete(h)

%% save the raw_data_export

Filename        = save_folder + "/raw_data_export_" + string(time_now) + "_" + string(terrain_type) + "_" + string(roi_select) + ".mat";

save(Filename, 'raw_data_export')


%% Compiling the map
% 
% disp("Making the map, sire...")
% pointCloudList = pccat([pointCloudList{:}]);

%% Displaying the map
% 
% hold on
% 
% % Plotting the line between the lidar and gps
% for point = 1:length(lidar_pos_store)
%     
%     plot3([lidar_pos_store(point,1) gps_pos_store(point,1)],...
%           [lidar_pos_store(point,2) gps_pos_store(point,2)],...
%           [lidar_pos_store(point,3) gps_pos_store(point,3)],...
%           'linewidth',3)
%       
% end
% 
% % Plotting the lidar and gps points
% scatter3(gps_pos_store(1,1),gps_pos_store(1,2),gps_pos_store(1,3),420,'^','MarkerFaceColor','yellow')
% scatter3(gps_pos_store(end,1),gps_pos_store(end,2),gps_pos_store(end,3),420,'^','MarkerFaceColor','blue')
% scatter3(gps_pos_store(:,1),gps_pos_store(:,2),gps_pos_store(:,3),50,'^','MarkerFaceColor','magenta')
% scatter3(lidar_pos_store(:,1),lidar_pos_store(:,2),lidar_pos_store(:,3),50,'^','MarkerFaceColor','cyan')
% 
% % Plotting the point cloud
% pcshow(pointCloudList);
% 
% view([0 0 90])

%% Save the PCD
% 
% save_ans = questdlg('Save pcd?', 'Save pcd?', 'Yes', 'No', 'No');
% 
% switch save_ans
%     
%     case 'Yes'
%         
%         name_ans        = inputdlg({'Enter Filename:'}, 'Filename', [1 35], {'pcd.pcd'});
%         name_ans        = name_ans{:};
%                 
%         export_dir      = uigetdir();
%         PCDFileName     = fullfile(export_dir, name_ans);
%         
%         pcwrite(pointCloudList,PCDFileName)
%         
%     case 'No'
%         
%         warning('WILL NOT SAVE THE PCD!')
%         
% end

%% End Program 

% web('https://www.youtube.com/watch?v=DPBvMsT3prg&ab_channel=AdesRizaTV')

% gong_gong()

disp('End Program!')



